# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: kimch0627.ImeBadge
PackageVersion: 1.7.1
InstallerLocale: ko-KR
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: ImeBadge
  Publisher: kimch0627
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
  InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kimch0627/windows-ime-badge/releases/download/v1.7.1/ImeBadge-Setup-1.7.1-x64.exe
  InstallerSha256: C2C2A56A4ADF6563D0156521D73F69A70E038EECBF395B9BA07A4E2E87805F1F
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
- Architecture: arm64
  InstallerUrl: https://github.com/kimch0627/windows-ime-badge/releases/download/v1.7.1/ImeBadge-Setup-1.7.1-arm64.exe
  InstallerSha256: 9C24DBF1A6CF67B721340BB643FEFEAB240949F8B1EEC962E5195C25F86242A4
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-28
