# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: kimch0627.ImeBadge
PackageVersion: 1.13.0
InstallerLocale: ko-KR
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: ImeBadge
  Publisher: kimch0627
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
  InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kimch0627/windows-ime-badge/releases/download/v1.13.0/ImeBadge-Setup-1.13.0-x64.exe
  InstallerSha256: 484E0CF6155C5B4EEA8326DC9B6E23E1F96DD1BCB6B9E23A964CB05DB484A7FF
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
- Architecture: arm64
  InstallerUrl: https://github.com/kimch0627/windows-ime-badge/releases/download/v1.13.0/ImeBadge-Setup-1.13.0-arm64.exe
  InstallerSha256: 369135523AEB271A82021DD4778495D5883487F826755856DCEE387ACBDCEFDA
  ProductCode: '{7E2C1D7A-9B1E-4E63-9A2B-5F1C0B7D3A21}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-02
